---
- name: Upgrade all packages
  become: true
  changed_when: false
  ansible.builtin.package:
    name: "*"
    update_cache: true
    state: latest

- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ prerequisite_packages }}"
