---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Update package cache.
      ansible.builtin.package:
        update_cache: true

    - name: Include office_tools role
      include_role:
        name: office_tools
