---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Update package cache generically.
      ansible.builtin.package:
        update_cache: true

- name: Import playbook
  ansible.builtin.import_playbook: ../../playbook.yaml
