---
# From https://ansible.readthedocs.io/projects/molecule/examples/podman/#config-playbook
dependency:
  name: galaxy
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: fedora41-container
    image: "docker.io/skalador/fedora41-ansible:latest"
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
